services:
  dev:
    container_name: development
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfileの場所を指定（デフォルトでDockerfileを探すので、省略可能）
    environment:
      - DEBUG=True  # 必要に応じて環境変数を設定
    entrypoint: ["/usr/local/bin/entrypoint.sh", "-c", "while true; do sleep 1; done"]
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:c